### ISSUE TITLE
Add query namespace support

### ISSUE THREAD

**Issue by mprokopov** [babashka/pod-babashka-etaoin#10]
http://etaoin.grishaev.me/etaoin.query.html

It would be nice to have `query` namespace as well in `babashka-etaoin` pod.

**Comment by borkdude** [comment]
Feel free to add

**Comment by borkdude** [comment]
I'll wait for this one before the next release

**Comment by borkdude** [comment]
I'm wondering if we should expose this since etaoin has an explicit api and api2 namespace. If these functions are not exposed through the API maybe they are considered to not be part of the API? 

/cc @igrishaev

**Comment by borkdude** [comment]
I haven't had an answer, so I'd say, let's just expose it.

**Comment by igrishaev** [comment]
Sorry @borkdude I was on my NY holidays. It's OK to expose the `query` namespace.

**Comment by igrishaev** [comment]
Actually, the primary namespace in Etaoin is the `.api` one. The `.api2` carries the new versions of macros that cannot be fixed in the `.api` without breaking the things. The `.api` namespace requires the `.query` ns.

**Comment by borkdude** [comment]
@igrishaev Thank you for the reply! Are you saying that the query functions are available already in the API ns?

**Comment by igrishaev** [comment]
Yes @borkdude , the `.api` ns imports the `.query`: https://github.com/igrishaev/etaoin/blob/master/src/etaoin/api.clj#L23

**Comment by borkdude** [comment]
Yes, the API namespaces _uses_ the query namespace, but this isn't what I'm asking. I'm asking if it _exposes_ the query namespace. So if you want to use a function from query, is it available via API?

**Comment by igrishaev** [comment]
Well, it looks like query functions are available only from the `.query` ns. I'm a bit unsure what does the `expose` word mean. Did you mean something like:

```
;; api.clj

(def expand query/expand)
;; and so on?
```

**Comment by borkdude** [comment]
Yes, that's what I mean :) If there is an API, I would expect all functions that are intended as the API to be available there, but I could be wrong.

**Comment by igrishaev** [comment]
Well, it's not so at the moment. Should a user need any of the `.query` functions, he or she needs to require it manually. Does it cause an issue for the babashka pod?

**Comment by borkdude** [comment]
No not at all. My only question was: is that `etaoin.query` namespace intended to be used by library users, given that you also have an explicit `api` namespace. It seems the answer is still yes. So let's expose it in the pod.

**Comment by borkdude** [comment]
@mprokopov I added `query/expand` to the master branch now. Is this the only var you want, or are there more?

**Comment by mprokopov** [comment]
Looks great, @borkdude! 
This is totally enough and thanks for your efforts!

**Comment by borkdude** [comment]
@mprokopov This is released now as 0.1.0.
